spring:
  application:
    name: configServer
  profiles:
    #    active: native
    active: git
  cloud:
    config:
      server:
        native:
        #          search-locations: "classpath:/config"
        #          search-locations: "file:///<file-path>"
        git:
          uri: #Add Github Repo URL with config files
          default-label: main
          username: #Github username
          password: #Add password/token to access repo
          #          searchPaths: config
          timeout: 5
          clone-on-start: true
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

#encrypt:
#  key: ""