build:
  version: "3.1"

loans:
  message: "Welcome to Bank LOANS related to LOCAL APIs"
  contactDetails:
    name: "John Doe"
    email: "john-doe@bankms.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 987-6543





