build:
  version: "2.0"

accounts:
  message: "Welcome to Bank ACCOUNTS related to QA APIs"
  contactDetails:
    name: "Ralphie Matt"
    email: "matt.r@bankms.com"
  onCallSupport:
    - (777) 111-5432
    - (777) 345-6789




