build:
  version: "3.0"

accounts:
  message: "Welcome to Bank ACCOUNTS related to local APIs"
  contactDetails:
    name: "John Doe"
    email: "john-doe@bankms.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 987-6543




