build:
  version: "1.0"

accounts:
  message: "Welcome to Bank ACCOUNTS related to prod APIs"
  contactDetails:
    name: "Aditya Chaurasia"
    email: "chauri@bankms.com"
  onCallSupport:
    - (666) 000-7654
    - (666) 789-4321




