build:
  version: "2.2"

cards:
  message: "Welcome to Bank CARDS related to QA APIs"
  contactDetails:
    name: "Shreya Patel"
    email: "shreya.p@bankms.com"
  onCallSupport:
    - (777) 111-5432
    - (777) 345-6789




