build:
  version: "1.1"

loans:
  message: "Welcome to Bank LOANS related to prod APIs"
  contactDetails:
    name: "Aditya Chaurasia"
    email: "chauri@bankms.com"
  onCallSupport:
    - (666) 000-7654
    - (666) 789-4321




