spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.1"

loans:
  message: "Welcome to Bank LOANS related to QA APIs"
  contactDetails:
    name: "Ralphie Matt"
    email: "matt.r@bankms.com"
  onCallSupport:
    - (777) 111-5432
    - (777) 345-6789




