spring:
  application:
    name: "apigateway"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false #To stop default routes
          lowerCaseServiceId: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

info:
  app:
    name: "apigateway"
    description: "Api Gateway for Bank microservices"
    version: "1.0.0"

logging:
  level:
    com:
      chauri:
        apigateway: DEBUG